# Generated by Django 5.2.9 on 2025-12-24 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0003_subscribe"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lesson",
            old_name="video",
            new_name="video_url",
        ),
    ]
